export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL";
export const ADD_COMPANY_RESET = "ADD_COMPANY_RESET";

export const DETAIL_COMPANY_REQUEST = "DETAIL_COMPANY_REQUEST";
export const DETAIL_COMPANY_SUCCESS = "DETAIL_COMPANY_SUCCESS";
export const DETAIL_COMPANY_FAIL = "DETAIL_COMPANY_FAIL";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET";
